# Generated by Django 3.2.4 on 2022-11-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='atime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
