# Generated by Django 3.2.4 on 2022-10-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('dates', models.DateField(auto_now_add=True)),
                ('datetime', models.DateTimeField(verbose_name='')),
                ('filepath', models.FilePathField(verbose_name='')),
                ('ipadd', models.GenericIPAddressField()),
                ('nullboolean', models.NullBooleanField(default=False)),
                ('file', models.FileField(upload_to='media')),
                ('ctime', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '书籍'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '出版社'},
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=100, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(blank=True, to='app01.Book'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='不要写外国名', max_length=64, verbose_name='名称aa'),
        ),
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.CharField(default='男', max_length=4, verbose_name='性别'),
        ),
    ]
