# Generated by Django 3.2.4 on 2022-11-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20221031_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ctime',
            options={'verbose_name_plural': '时间'},
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.CharField(max_length=4, verbose_name='性别'),
        ),
    ]
