# Generated by Django 3.2.4 on 2022-11-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20221101_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='boolean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bools', models.BooleanField(default=False)),
            ],
        ),
    ]
