# Generated by Django 3.2.4 on 2022-11-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_boolean'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ctime',
            new_name='cctime',
        ),
    ]
