# Generated by Django 3.2.4 on 2022-11-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_rename_ctime_cctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctime',
            name='now_add_datetime',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cctime',
            name='now_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cctime',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cctime',
            name='filepath',
            field=models.FilePathField(blank=True, path='D:\\C#\\python\\Django\\django_2022\\bms\\media'),
        ),
    ]
