# Generated by Django 3.2.4 on 2022-11-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20221101_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bools', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('dates', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='boolean',
        ),
        migrations.RemoveField(
            model_name='cctime',
            name='nullboolean',
        ),
    ]
