# Generated by Django 3.2.4 on 2022-11-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20221101_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_time',
            name='date',
        ),
        migrations.RemoveField(
            model_name='add_time',
            name='dates',
        ),
        migrations.AddField(
            model_name='add_time',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
