# Generated by Django 3.2.4 on 2022-11-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_remove_add_time_change_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_time1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bools', models.BooleanField(default=False)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('datetime', models.DateTimeField()),
                ('ctime', models.TimeField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='add_time',
        ),
    ]
