# Generated by Django 3.2.4 on 2022-10-28 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=18, verbose_name='身份证号')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('sex', models.CharField(max_length=4, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('label', models.CharField(max_length=100, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'verbose_name_plural': '身份证表',
                'db_table': 'idcard',
            },
        ),
    ]
