# Generated by Django 3.2.4 on 2022-10-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='app',
            field=models.ManyToManyField(to='onetomany.App'),
        ),
    ]
